// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcelTracker.Infrastructure.Contexts;

#nullable disable

namespace ParcelTracker.Infrastructure.Migrations.Rules
{
    [DbContext(typeof(RulesContext))]
    [Migration("20240516202143_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.30");

            modelBuilder.Entity("ParcelTracker.Infrastructure.Entities.RuleEntity", b =>
                {
                    b.Property<long>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultEmailFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultEmailTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RuleId");

                    b.ToTable("Rules", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
